In [2]:
import pandas as pd
import numpy as np

In [3]:
gallup = pd.read_csv('data/USAIPO1936-0053.csv')

In [4]:
gallup.head()

,form,state,region,female,age,class,OCCUPATION1,OCCUPATION2,OCCUPATION3,black,...,StPOAbrv,SOUTH11,SOUTH11xBLACK,SOUTH12,SOUTH12xBLACK,south,SOUTHxBLACK,year,WtPubFeas,WtVotFeas
0,NaN,Indiana,East Central,Male,NaN,Av+,Skilled workers,NaN,NaN,NaN,...,in,Non-South,NaN,Non-South,NaN,Non-South,NaN,1936,NaN,NaN
1,NaN,Illinois,East Central,Male,NaN,Av+,Skilled workers,NaN,NaN,NaN,...,il,Non-South,NaN,Non-South,NaN,Non-South,NaN,1936,NaN,NaN
2,NaN,Michigan,East Central,Male,NaN,Av,Business,NaN,NaN,NaN,...,mi,Non-South,NaN,Non-South,NaN,Non-South,NaN,1936,NaN,NaN
3,NaN,Virginia,South and Southwest,Male,55 yrs and over,P or P+,Skilled workers,NaN,NaN,NaN,...,va,South,NaN,South,NaN,South,NaN,1936,NaN,NaN
4,NaN,Florida,South and Southwest,Male,55 yrs and over,Av+,Skilled workers,NaN,NaN,NaN,...,fl,South,NaN,South,NaN,South,NaN,1936,NaN,NaN