In [19]:
import pandas as pd
import numpy as np

In [20]:
gallup = pd.read_csv('data/USAIPO1936-0053.csv')

In [21]:
gallup.head()

,form,state,region,female,age,class,OCCUPATION1,OCCUPATION2,OCCUPATION3,black,...,StPOAbrv,SOUTH11,SOUTH11xBLACK,SOUTH12,SOUTH12xBLACK,south,SOUTHxBLACK,year,WtPubFeas,WtVotFeas
0,NaN,Indiana,East Central,Male,NaN,Av+,Skilled workers,NaN,NaN,NaN,...,in,Non-South,NaN,Non-South,NaN,Non-South,NaN,1936,NaN,NaN
1,NaN,Illinois,East Central,Male,NaN,Av+,Skilled workers,NaN,NaN,NaN,...,il,Non-South,NaN,Non-South,NaN,Non-South,NaN,1936,NaN,NaN
2,NaN,Michigan,East Central,Male,NaN,Av,Business,NaN,NaN,NaN,...,mi,Non-South,NaN,Non-South,NaN,Non-South,NaN,1936,NaN,NaN
3,NaN,Virginia,South and Southwest,Male,55 yrs and over,P or P+,Skilled workers,NaN,NaN,NaN,...,va,South,NaN,South,NaN,South,NaN,1936,NaN,NaN
4,NaN,Florida,South and Southwest,Male,55 yrs and over,Av+,Skilled workers,NaN,NaN,NaN,...,fl,South,NaN,South,NaN,South,NaN,1936,NaN,NaN

In [22]:
abc = pd.read_stata("data/31120928.dta")
abc.head().T

,0,1,2,3,4
respid,260840001,260840002,260840003,260840004,260840005
weight_pid,0.7127,0.8026,0.9083,0.629,1.5029
complete_status,qualified,qualified,qualified,qualified,qualified
q1_1,unfavorable,unfavorable,favorable,favorable,unfavorable
q1_2,favorable,favorable,unfavorable,unfavorable,favorable
q2_1,disapprove,disapprove,approve,disapprove,disapprove
q2_2,disapprove,disapprove,approve,disapprove,approve
q2_3,approve,disapprove,approve,approve,disapprove
q2_4,disapprove,disapprove,approve,disapprove,disapprove
q2_5,disapprove,disapprove,approve,disapprove,disapprove
q2_6,approve,disapprove,approve,disapprove,approve
q2_7,disapprove,disapprove,approve,disapprove,disapprove
q2_8,disapprove,disapprove,approve,approve,disapprove
q2_9,disapprove,disapprove,approve,disapprove,disapprove
q3_1,approve,approve,disapprove,approve,approve
q3_2,disapprove,approve,disapprove,disapprove,approve
q3_3,approve,approve,disapprove,disapprove,approve
q3_4,approve,approve,disapprove,approve,approve
q3_5,approve,approve,disapprove,approve,disapprove
q3_7,disapprove,approve,disapprove,disapprove,disapprove
q3_8,approve,approve,disapprove,disapprove,approve
q4,donald trump,donald trump,joe biden,joe biden,donald trump
q5,the same as you expected,the same as you expected,better than you expected,"didnÂ’t read, see, or hear about the state of t...","didnÂ’t read, see, or hear about the state of t..."
qpid,a republican,a republican,a democrat,a democrat,a republican
ppworka,retired,retired,employed full-time (by someone else),employed full-time (by someone else),homemaker
abcage,65+,65+,65+,30-49,30-49
ppage,77,76,65,43,49
ppeducat,bachelors degree or higher,high school,high school,bachelors degree or higher,bachelors degree or higher
ppeduc5,masterÂ’s degree or above,high school graduate (high school diploma or t...,high school graduate (high school diploma or t...,bachelorÂ’s degree,bachelorÂ’s degree
ppethm,"white, non-hispanic","white, non-hispanic","black, non-hispanic","white, non-hispanic",hispanic
ppgender,male,female,male,female,female
pphhsize,2,1,2,1,6. six or more
pphouse4,one-family condo or townhouse attached to othe...,a one-family house detached from any other house,a one-family house detached from any other house,building with 2 or more apartments,a one-family house detached from any other house
ppinc7,"$150,000 or more","$50,000 to $74,999","$75,000 to $99,999","$25,000 to $49,999","$150,000 or more"
ppmarit5,widowed,now married,now married,never married,now married
ppmsacat,metro,metro,metro,metro,metro
ppreg4,west,south,south,south,midwest
ppreg9,pacific,south atlantic,south atlantic,south atlantic,west north central
pprent,owned or being bought by you or someone in you...,owned or being bought by you or someone in you...,owned or being bought by you or someone in you...,rented for cash,owned or being bought by you or someone in you...
ppstaten,california,florida,north carolina,delaware,iowa
ppemploy,not working,not working,working full-time,working full-time,not working
ppt18ov,2,1,2,1,3
ppkid017,0,0,0,0,6
xspanish,english,english,english,english,english
xparty4,independent,republican,democrat,democrat,independent
xurbanicity,urban,suburban,urban,suburban,urban
contact,"no, i am not willing to be interviewed","no, i am not willing to be interviewed","no, i am not willing to be interviewed","yes, i am willing to be interviewed","yes, i am willing to be interviewed"

In [37]:
width = pd.read_csv("data/USIA_data_widths.csv")

In [38]:
usia = pd.read_fwf("data/i20068.dat", widths = width["Width"], header = None)

In [39]:
usia

,0,1,2,3,4,5,6,7,8,9,...,126,127,128,129,130,131,132,133,134,135
0,1,155.0,2.0,1.0,2.0,108.0,1.0,2.0,1.0,4.0,...,3.0,1.0,5.0,6.0,2.0,4.0,4.0,NaN,NaN,6.0
1,2,155.0,2.0,1.0,2.0,120.0,NaN,9.0,1.0,3.0,...,3.0,1.0,6.0,6.0,1.0,NaN,NaN,NaN,NaN,NaN
2,3,155.0,2.0,1.0,2.0,102.0,1.0,4.0,NaN,NaN,...,2.0,1.0,5.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
3,4,155.0,2.0,1.0,2.0,129.0,NaN,9.0,1.0,3.0,...,2.0,1.0,6.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN
4,5,155.0,2.0,1.0,1.0,1.0,1.0,3.0,NaN,9.0,...,3.0,1.0,6.0,7.0,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2033,2248,283.0,2.0,2.0,2.0,102.0,NaN,6.0,1.0,1.0,...,5.0,1.0,21.0,7.0,2.0,5.0,7.0,NaN,NaN,7.0
2034,2249,283.0,2.0,2.0,8.0,NaN,9.0,8.0,NaN,NaN,...,1.0,1.0,51.0,7.0,2.0,4.0,1.0,NaN,NaN,1.0
2035,2250,283.0,2.0,2.0,9.0,NaN,9.0,8.0,NaN,NaN,...,4.0,1.0,31.0,7.0,2.0,3.0,6.0,NaN,NaN,4.0
2036,2251,255.0,1.0,2.0,2.0,163.0,NaN,9.0,NaN,6.0,...,4.0,1.0,11.0,7.0,2.0,3.0,6.0,NaN,NaN,1.0
2037,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN