# Lab Assignment 2: How to Load CSV, ASCII, and other data into Python
## DS 6001: Practice and Application of Data Science

### Instructions
Please answer the following questions as completely as possible using text, code, and the results of code as needed. Format your answers in a Jupyter notebook. To receive full credit, make sure you address every part of the problem, and make sure your document is formatted in a clean and professional way.

There are 11 data files attached to this lab assignment, with different extensions. First, download all of these data files, and save them in the same folder on your local machine. Your task in the following questions is to load each file into Python correctly, so that you can begin the process of data cleaning. If the variable names are included in the file, use those names to name the columns. If the variable names are not included, use these names in order:

In [56]:
column_names = ["Country", "Happiness score", "Whisker-high", "Whisker-low", 
  "Dystopia (1.92) + residual", "Explained by: GDP per capita", 
  "Explained by: Social support", "Explained by: Healthy life expectancy", 
  "Explained by: Freedom to make life choices", "Explained by: Generosity", 
  "Explained by: Perceptions of corruption" ]

If you loaded the data correctly, it will look like `data_clean.csv`, which is also attached to this lab.

## Problem 0
Import the libraries you will need. Then write code to change the working directory to the folder in which you saved the data files, run the code displayed above to create the `column_names` list, load `data_clean.csv`, and display the output of the `.info()` method of `data_clean`. (1 point)

In [57]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
os.chdir('/Users/Luke/MSDS/DS6001/Lab_2')
column_names = ["Country", "Happiness score", "Whisker-high", "Whisker-low", 
  "Dystopia (1.92) + residual", "Explained by: GDP per capita", 
  "Explained by: Social support", "Explained by: Healthy life expectancy", 
  "Explained by: Freedom to make life choices", "Explained by: Generosity", 
  "Explained by: Perceptions of corruption" ]
cleaned_data = pd.read_csv("data_clean.csv", names = column_names)
cleaned_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 11 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     157 non-null    object
 1   Happiness score                             157 non-null    object
 2   Whisker-high                                157 non-null    object
 3   Whisker-low                                 157 non-null    object
 4   Dystopia (1.92) + residual                  157 non-null    object
 5   Explained by: GDP per capita                157 non-null    object
 6   Explained by: Social support                157 non-null    object
 7   Explained by: Healthy life expectancy       157 non-null    object
 8   Explained by: Freedom to make life choices  157 non-null    object
 9   Explained by: Generosity                    157 non-null    object
 10  Explained by: Perceptions of corruption     157 non-null    object
dtypes: object(11)
memory usage: 13.6+ KB

## Problem 1
Load `data1.csv`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (1 point)

In [58]:
data1 = pd.read_csv("data1.csv")
data1

,"Source: The World Happiness Report (2018), The Sustainable Development Solutions Network (SDSN)",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,URL: http://worldhappiness.report/ed/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
2,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
3,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
4,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
...,...,...,...,...,...,...,...,...,...,...,...
153,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
154,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
155,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
156,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
157,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

This file incorrectly labeled the first two rows, one as the header with source information and the second row with the URL. The data starts on the third row with the header, so we need to replace the header with the correct header and drop the first two rows.

In [59]:
data1 = pd.read_csv("data1.csv", skiprows = 2)
data1

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

## Problem 2
Load `data2.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (1 point)

In [60]:
data2 = pd.read_table("data2.txt",skiprows=2, sep =',')
data2 = data2.drop([0])
data2

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
1,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
2,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
3,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
4,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
5,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
154,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
155,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
156,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
157,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
158,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

## Problem 3
Load `data3.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (1 point)

In [61]:
data3 = pd.read_table("data3.txt",skiprows=2)
data3

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

## Problem 4
Load `data4.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (1 point)

In [62]:
data4 = pd.read_table("data4.txt", sep = "$", names = column_names)
data4

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

## Problem 5
Load `data5.csv`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (1 point)

In [63]:
data5 = pd.read_csv("data5.csv")
data5 = data5.drop([156,157])
data5

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

## Problem 6
Load `data6.dat`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (1 point)

In [64]:
data6 = pd.read_csv("data6.dat",delimiter = ",", na_values = 999.000)
data6

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,NaN,NaN,NaN,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,NaN,NaN,1.582,NaN,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,NaN,0.683,0.284,0.408
3,Iceland,7.495,7.593,NaN,2.426,1.343,1.644,0.914,0.677,0.353,NaN
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,NaN,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,NaN,0.064
152,Tanzania,NaN,NaN,3.193,0.628,NaN,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,NaN,3.123,1.691,0.337,NaN,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,NaN,0.038
155,Burundi,2.905,3.074,NaN,1.752,0.091,NaN,0.145,0.065,0.149,0.076

## Problem 7
Load `data7.xlsx`, which is an Excel file. Keep only the sheet named “Data”. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (2 points)

In [65]:
data7 = pd.read_excel("data7.xlsx", sheet_name = "Data")
data7

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

## Problem 8
Load `data8.dta`, which is a Stata 13 file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (2 points)

In [66]:
data8 = pd.read_stata("data8.dta")
data8.columns = column_names
data8

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

## Problem 9
Load `data9.sav`, which is an SPSS file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (2 points)

In [71]:
data9 = pd.read_spss("data9.sav")
data9.columns = column_names
data9

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

## Problem 10
Load `data10.xpt`, which is a SAS file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (If some of the country names display as `b'Finland'`, don't worry aout that.) (2 points)

In [75]:
data10 = pd.read_sas("data10.xpt")
data10.columns = column_names
data10

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,b'Finland',7.632,7.695,7.569,2.595,1.305,1.592000e+00,0.874,0.681,0.192,0.393
1,b'Norway',7.594,7.657,7.530,2.383,1.456,1.582000e+00,0.861,0.686,0.286,0.340
2,b'Denmark',7.555,7.623,7.487,2.370,1.351,1.590000e+00,0.868,0.683,0.284,0.408
3,b'Iceland',7.495,7.593,7.398,2.426,1.343,1.644000e+00,0.914,0.677,0.353,0.138
4,b'Switzerland',7.487,7.570,7.405,2.320,1.420,1.549000e+00,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...,...,...
151,b'Yemen',3.355,3.448,3.262,1.106,0.442,1.073000e+00,0.343,0.244,0.083,0.064
152,b'Tanzania',3.303,3.414,3.193,0.628,0.455,9.910000e-01,0.381,0.481,0.270,0.097
153,b'South Sudan',3.254,3.385,3.123,1.691,0.337,6.080000e-01,0.177,0.112,0.224,0.106
154,b'Central African Republic',3.083,3.227,2.939,2.487,0.024,5.397605e-79,0.010,0.305,0.218,0.038
155,b'Burundi',2.905,3.074,2.735,1.752,0.091,6.270000e-01,0.145,0.065,0.149,0.076

## Problem 11
Please load the `data11.txt` file, which is a fixed width file. The columns are defined as follows:

| Variable                                   | Width | Start | End |
|--------------------------------------------|-------|-------|-----|
| Country                                    | 24    | 1     | 24  |
| Happiness score                            | 5     | 25    | 29  |
| Whisker-high                               | 5     | 30    | 34  |
| Whisker-low                                | 5     | 35    | 39  |
| Dystopia (1.92) + residual                 | 5     | 40    | 44  |
| Explained by: GDP per capita               | 5     | 45    | 49  |
| Explained by: Social support               | 5     | 50    | 54  |
| Explained by: Healthy life expectancy      | 5     | 55    | 59  |
| Explained by: Freedom to make life choices | 5     | 60    | 64  |
| Explained by: Generosity                   | 5     | 65    | 69  |
| Explained by: Perceptions of corruption    | 5     | 70    | 74  |

Then save the this loaded data frame as a CSV file on your local machine. Be sure to use a unique filename so as not to overwrite any existing files. (5 points)